Models/Archive.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.Models
{
    // 文章
    public class Archive
    {
        // 文章编号
        [Key]
        public int Aid { get; set; }
        // 标题
        [Required(ErrorMessage = "必须输入标题")]
        public string Title { get; set; }
        // 创建时间
        [Required]
        public DateTime Created { get; set; }
        // 内容
        [DefaultValue(null)]
        public string Text { get; set; }
        // 作者ID
        public string Uid { get; set; }
        // 查看数
        [DefaultValue(0)]
        public int Views { get; set; }
        // 评论数
        [DefaultValue(0)]
        public int CommentsNum { get; set; }
        // 头图
        public string TitleImage { get; set; }
    }
}

Models/Feed.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.Models
{
    // 文章
    public class Feed
    {
        // 编号
        [Key]
        public int Fid { get; set; }
        // 内容
        [Required(ErrorMessage = "必须输入内容")]
        public string Text { get; set; }
        // 创建时间
        [Required]
        public DateTime Created { get; set; }
        // 作者ID
        public string Uid { get; set; }
        // 点赞数
        [DefaultValue(0)]
        public int Likes { get; set; }
    }
}

Models/Friend.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.Models
{
    // 友链站点
    public class Friend
    {
        [Key]
        public int Fid { get; set; }
        // 名称
        [Required(ErrorMessage = "必须输入名称")]
        public string Name { get; set; }
        // 链接
        [Required(ErrorMessage = "必须输入链接")]
        [Url(ErrorMessage = "链接格式错误")]
        public string Url { get; set; }
        // 图标
        public string Avatar { get; set; }
        // 简介
        public string Introduce { get; set; }
    }
}

ViewModels/ArchiveViewModel.cs
using FluentBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.ViewModels
{
    public class ArchiveViewModel
    {
        public Archive Archive { get; set; }
        public User Author { get; set; }
        public List<Meta> Categories { get; set; }
        public List<Meta> Tags { get; set; }
        public string DefaultTitleImage { get; set; }
        public string Url { get; set; }

        public readonly List<string> CategoryColors = new List<string>()
        {
            "btn-outline-primary",
            "btn-outline-success",
            "btn-outline-danger",
            "btn-outline-warning",
            "btn-outline-info"
        };
    }
}

ViewModels/FeedViewModel.cs
using FluentBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.ViewModels
{
    public class FeedViewModel
    {
        public List<Feed> Feeds { get; set; }
        public List<User> Authors { get; set; }
        public int FeedsCount { get; set; }
        public List<bool> LikedList { get; set; }
    }
}

ViewModels/FriendViewModel.cs
using FluentBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.ViewModels
{
    public class FriendViewModel
    {
        public List<Friend> Friends { get; set; }
        public int FriendsCount { get; set; }
        public string Notice { get; set; }
    }
}

ViewModels/HomeViewModel.cs
using FluentBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FluentBlog.ViewModels
{
    public class HomeViewModel
    {
        public Meta CurrentMeta { get; set; }
        public List<Archive> Archives { get; set; }
        public List<User> Authors { get; set; }
        public List<List<Meta>> Categories { get; set; }
        public int PageNum { get; set; }
        public int PageCount { get; set; }

        public readonly List<string> CategoryColors = new List<string>()
        {
            "btn-outline-primary",
            "btn-outline-success",
            "btn-outline-danger",
            "btn-outline-warning",
            "btn-outline-info"
        };
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FluentBlog.DataRepositories;
using FluentBlog.Models;
using FluentBlog.ViewModels;
using FluentBlog.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;

namespace FluentBlog.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IRelationshipRepository _relationshipRepository;
        private readonly IMetaRepository _metaRepository;
        private readonly IArchiveRepository _archiveRepository;
        private readonly UserManager<User> _userManager;
        private readonly ISettingRepository _settingRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IFeedRepository _feedRepository;
        private readonly IFriendRepository _friendRepository;
        private readonly IHttpClientFactory _clientFactory;

        public HomeController(IRelationshipRepository relationshipRepository, IMetaRepository metaRepository,
            IArchiveRepository archiveRepository, UserManager<User> userManager,
            ISettingRepository settingRepository, IHttpContextAccessor httpContextAccessor,
            IFeedRepository feedRepository, IFriendRepository friendRepository, IHttpClientFactory clientFactory) :
            base(settingRepository)
        {
            _metaRepository = metaRepository;
            _relationshipRepository = relationshipRepository;
            _archiveRepository = archiveRepository;
            _userManager = userManager;
            _settingRepository = settingRepository;
            _httpContextAccessor = httpContextAccessor;
            _feedRepository = feedRepository;
            _friendRepository = friendRepository;
            _clientFactory = clientFactory;
        }

        // 首页
        [Route("")]
        // 全部文章
        [Route("/page/{page}")]
        // 分类下的文章
        [Route("/meta/{slug}/{page?}")]
        public IActionResult Index(int? page, string slug = null)
        {
            // 获取用户设置的每页包含文章数
            var settings = _settingRepository.GetSettings();
            int archivesCountPerPage = Convert.ToInt32(settings["ArchivesCountPerPage"]);

            HomeViewModel homeViewModel;

            // 未选择分类
            if (slug == null)
            {
                // 得到总页数
                int pageCount = _archiveRepository.GetArchivesCount() / archivesCountPerPage + 1;
                if (page != null && page > pageCount)
                {
                    return NotFound();
                }

                // 得到文章详情
                List<Archive> archives = _archiveRepository.GetArchivesByPage(page ?? 1, archivesCountPerPage);
                List<User> authors = new List<User>();
                List<List<Meta>> categories = new List<List<Meta>>();
                foreach (var archive in archives)
                {
                    archive.Text = _archiveRepository.MarkdownToPlainText(archive.Text);
                    if (string.IsNullOrEmpty(archive.TitleImage))
                    {
                        archive.TitleImage = _archiveRepository.GetDefaultTitleImage();
                    }

                    authors.Add(_userManager.FindByIdAsync(archive.Uid).Result);
                    categories.Add(_relationshipRepository.GetMetasByArchiveId(archive.Aid, MetaType.Category));
                }

                homeViewModel = new HomeViewModel()
                {
                    Archives = archives,
                    Authors = authors,
                    Categories = categories,
                    PageNum = page ?? 1,
                    PageCount = pageCount
                };
                if (page == null || page == 1)
                {
                    ViewBag.Title = "";
                }
                else
                {
                    ViewBag.Title = "第" + page + "页" + " - ";
                }
            }
            // 选择分类
            else
            {
                // 得到当前分类
                Meta currentMeta = _metaRepository.GetMetaBySlug(slug);
                if (currentMeta == null)
                {
                    return NotFound();
                }

                // 得到总页数
                int pageCount = _metaRepository.GetArchiveOfMetaCount(currentMeta.Mid) / archivesCountPerPage + 1;
                if (page != null && page > pageCount)
                {
                    return NotFound();
                }

                // 得到文章详情
                List<Archive> archives =
                    _metaRepository.GetArchivesByMetaAndPage(currentMeta.Mid, page ?? 1, archivesCountPerPage);
                List<User> authors = new List<User>();
                List<List<Meta>> categories = new List<List<Meta>>();
                foreach (var archive in archives)
                {
                    archive.Text = _archiveRepository.MarkdownToPlainText(archive.Text);
                    if (string.IsNullOrEmpty(archive.TitleImage))
                    {
                        archive.TitleImage = _archiveRepository.GetDefaultTitleImage();
                    }

                    authors.Add(_userManager.FindByIdAsync(archive.Uid).Result);
                    categories.Add(_relationshipRepository.GetMetasByArchiveId(archive.Aid, MetaType.Category));
                }

                homeViewModel = new HomeViewModel
                {
                    CurrentMeta = currentMeta,
                    Archives = archives,
                    Authors = authors,
                    Categories = categories,
                    PageNum = page ?? 1,
                    PageCount = pageCount
                };
                if (page == null || page == 1)
                {
                    ViewBag.Title = currentMeta.Name + " - ";
                }
                else
                {
                    ViewBag.Title = "第" + page + "页" + " - " + currentMeta.Name + " - ";
                }
            }

            return View(homeViewModel);
        }

        // 文章页
        [Route("/archive/{aid}")]
        public IActionResult Archive(int aid)
        {
            Archive archive = _archiveRepository.GetArchiveById(aid);
            //判断文章是否存在
            if (archive == null)
            {
                return NotFound();
            }

            // 增加阅读量
            try
            {
                if (!Convert.ToBoolean(HttpContext.Session.GetString("ViewArchive" + aid)))
                {
                    throw new FormatException();
                }
            }
            catch (FormatException)
            {
                archive = _archiveRepository.AddViewsCount(archive);
                HttpContext.Session.SetString("ViewArchive" + aid, "True");
            }

            // 查询作者
            User author = _userManager.FindByIdAsync(archive.Uid).Result;
            List<Meta> categories = _relationshipRepository.GetMetasByArchiveId(archive.Aid, MetaType.Category);
            List<Meta> tags = _relationshipRepository.GetMetasByArchiveId(archive.Aid, MetaType.Tag);

            ArchiveViewModel archiveViewModel = new ArchiveViewModel
            {
                Archive = archive,
                Author = author,
                DefaultTitleImage = _archiveRepository.GetDefaultTitleImage(),
                Url = _httpContextAccessor.HttpContext?.Request.GetDisplayUrl(),
                Categories = categories,
                Tags = tags
            };
            ViewBag.Title = archive.Title + " - ";
            //将ViewModel对象传递给View()方法
            return View(archiveViewModel);
        }

        // 更新评论数
        [HttpGet]
        public JsonResult UpdateCommentsCount(string url)
        {
            var settings = _settingRepository.GetSettings();
            // 请求获取评论数
            var request = new HttpRequestMessage(HttpMethod.Get,
                "/1.1/classes/Comment?where={\"url\":\"" + url + "\"}&count=1&limit=0");
            var client = _clientFactory.CreateClient("leanCloudClient");
            client.BaseAddress = new Uri(settings["LeanCloudAPIUrl"]);
            client.DefaultRequestHeaders.Add("X-LC-Id", settings["LeanCloudAppID"]);
            client.DefaultRequestHeaders.Add("X-LC-Key", settings["LeanCloudAppKey"]);
            var response = client.SendAsync(request);
            var resultString = response.Result.Content.ReadAsStringAsync();
            var result = JsonSerializer.Deserialize<Dictionary<string, dynamic>>(resultString.Result);

            // 更新至数据库
            string[] urlSplit = url.Split('/');
            if (result != null && string.Equals(urlSplit[^2], "archive", StringComparison.CurrentCultureIgnoreCase))
            {
                Archive archive = _archiveRepository.GetArchiveById(Convert.ToInt32(urlSplit.Last()));
                archive.CommentsNum = Convert.ToInt32(result["count"].ToString());
                _archiveRepository.Update(archive);
                return Json(archive.CommentsNum);
            }

            return Json(-1);
        }

        // 动态
        [Route("/feed")]
        public IActionResult Feed()
        {
            List<Feed> feeds = _feedRepository.GetAllFeeds();
            if (feeds == null)
            {
                return Content("");
            }

            List<User> authors = feeds.Select(feed => _userManager.FindByIdAsync(feed.Uid).Result).ToList();
            List<bool> likedList = new List<bool>();
            foreach (var feed in feeds)
            {
                bool liked;
                try

ViewComponents/ContactBlockViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentBlog.DataRepositories;
using FluentBlog.Models;
using FluentBlog.ViewModels;
using System.Text.Json;

namespace FluentBlog.ViewComponents
{
    // 联系方式
    public class ContactBlockViewComponent : ViewComponent
    {
        private readonly ISettingRepository _settingRepository;

        public ContactBlockViewComponent(ISettingRepository settingRepository)
        {
            _settingRepository = settingRepository;
        }

        public IViewComponentResult Invoke()
        {
            var settings = _settingRepository.GetSettings();
            var contacts = JsonSerializer.Deserialize<List<Dictionary<string, string>>>(settings["Contacts"]);
            ContactViewModel contactViewModel = new ContactViewModel
            {
                Contacts = contacts
            };
            return View(contactViewModel);
        }
    }
}

ViewComponents/FeedBlockViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentBlog.DataRepositories;
using FluentBlog.Models;
using Microsoft.AspNetCore.Http;
using FluentBlog.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace FluentBlog.ViewComponents
{
    public class FeedBlockViewComponent : ViewComponent
    {
        private readonly IFeedRepository _feedRepository;
        private readonly UserManager<User> _userManager;

        public FeedBlockViewComponent(IFeedRepository feedRepository, UserManager<User> userManager)
        {
            _feedRepository = feedRepository;
            _userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            List<Feed> feeds = new List<Feed>();
            List<User> authors = new List<User>();
            List<bool> likedList = new List<bool>();
            var lastFeed = _feedRepository.GetLastFeed();
            if (lastFeed == null)
            {
                return Content("");
            }

            bool liked;
            try
            {
                liked = Convert.ToBoolean(HttpContext.Session.GetString("LikeFeed" + lastFeed.Fid));
            }
            catch (FormatException)
            {
                liked = false;
            }
            likedList.Add(liked);
            feeds.Add(lastFeed);
            authors.Add(_userManager.FindByIdAsync(lastFeed.Uid).Result);
            FeedViewModel feedViewModel = new FeedViewModel
            {
                LikedList = likedList,
                Feeds = feeds,
                Authors = authors
            };
            return View(feedViewModel);
        }
    }
}

Views/Home/About.cshtml
@section HeadScripts{
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/editor.md/css/editormd.preview.css" />
        <script src="~/lib/editor.md/editormd.js"></script>
        <script src="~/lib/editor.md/lib/marked.min.js"></script>
        <script src="~/lib/editor.md/lib/prettify.min.js"></script>
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yremp/editormd/css/editormd.preview.css" />
        <script src="https://cdn.jsdelivr.net/gh/yremp/editormd/editormd.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/yremp/editormd/lib/marked.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/yremp/editormd/lib/prettify.min.js"></script>
    </environment>
}


<div class="card mb-4 shadow">
    <!--主体-->
    <div class="card-body">
        <div class="p-3">
            <!--标题-->
            <h2 class="card-title font-weight-bold mb-2 mt-3">
                关于
            </h2>
        </div>
        <hr>
        <!--正文-->
        <div id="description" class="font-weight-normal">
            <!--加载动画-->
            <div class="progress-cover progress-cover-primary" id="progress-cover">
                <br />
                <br />
                <div class="progress progress-medium fluent-position">
                    <span class="progress-span"></span>
                    <span class="progress-span"></span>
                    <span class="progress-span"></span>
                    <span class="progress-span"></span>
                    <span class="progress-span"></span>
                    <span class="progress-span"></span>
                </div>
                <br />
                <br />
            </div>
            <!--正文-->
            <textarea style="display: none;">@ViewBag.About</textarea>
        </div>
    </div>
</div>

@section SecondSidebar{
    <!-- 联系方式栏 -->
    @if (ViewBag.Settings["Contacts"] != "[]")
    {
        @(await Component.InvokeAsync("ContactBlock"))
    }
}
@section BottomScripts{
    <script type="text/javascript">
        $(function () {
            var editormdView = editormd.markdownToHTML("description",
                {
                    htmlDecode: true
                });
            $('.progress-cover').css('display', 'none');
        });
    </script>
}

Views/Home/Feed.cshtml
@model FluentBlog.ViewModels.FeedViewModel
@{ bool isLeft = false; }

@section HeadScripts{
    <link rel="stylesheet" type="text/css" href="css/timeline.css"/>
    <script type="text/javascript" src="js/timeline.js"></script>
    <script>
        function addLikesCount(fid) {
            $.ajax({
                url: '@Url.Action("AddFeedLikesCount", "Home")',
                type: 'GET',
                dataType: 'json',
                cache: false,
                data: { fid: fid },
                success: function(feed) {
                    $(`#likes-${fid}`).addClass("text-primary");
                    $(`#likes-${fid}`).removeAttr("href");
                    $(`#likes-${fid}`).removeAttr("onclick");
                    $(`#likesIcon-${fid}`).attr("data-original-title", "已赞");
                    $(`#likesCount-${fid}`).text(feed["likes"]);
                }
            });
        }
    </script>
}

<div class="card mb-4 shadow">
    <div class="card-body">
        <div class="p-3">
            <!--标题-->
            <h2 class="card-title font-weight-bold mb-2 mt-3">
                动态
            </h2>
            <p>当前博客共收录动态@(Model.FeedsCount)条</p>
        </div>
        <hr>
        <div class="VivaTimeline">
            <dl>
                @for (int i = 0; i < Model.Feeds.Count; i++)
                {
                    if (i == 0 || Model.Feeds[i].Created.ToString("y") != Model.Feeds[i - 1].Created.ToString("y"))
                    {
                        isLeft = !isLeft;
                        <dt class="bg-gray">@Model.Feeds[i].Created.ToString("y")</dt>
                    }
                    <dd class="@(isLeft ? "pos-left" : "pos-right") clearfix pt-3">
                        <div class="circ bg-primary"></div>
                        <div class="time text-primary">
                            @Model.Feeds[i].Created.ToString("d日")
                            <br/>
                            @Model.Feeds[i].Created.ToString("dddd")
                        </div>
                        <div class="events card bg-white" style="width: 47%">
                            <div class="card-body p-1 p-sm-3">
                                <blockquote class="blockquote p-1 p-sm-2 mt-2">
                                    <!-- 博主 -->
                                    <h6 class="font-weight-bold">@@@Model.Authors[i].DisplayName：</h6>
                                    <!-- 动态内容 -->
                                    <p class="mb-1 small">@Model.Feeds[i].Text</p>
                                    <div class="float-right">
                                        <!-- 时间 -->
                                        <span class="text-muted small d-none d-sm-inline">
                                            <i class="mi mi-ClockLegacy small" data-toggle="tooltip" data-placement="top" title="发布时间"></i> @Model.Feeds[0].Created.ToString("T")
                                        </span>
                                        &nbsp;
                                        <!-- 点赞 -->
                                        @if (Model.LikedList[i])
                                        {
                                            <a class="text-muted text-primary small" id="@("likes-" + Model.Feeds[i].Fid)">
                                                <i class="mi mi-Like small" data-toggle="tooltip" data-placement="top" title="已赞" id="@("likesIcon-" + Model.Feeds[i].Fid)"></i>
                                                <span id="@("likesCount-" + Model.Feeds[i].Fid)">@Model.Feeds[i].Likes</span>
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="text-muted small" onclick="addLikesCount(@Model.Feeds[i].Fid)" href="javascript:void(0);" id="@("likes-" + Model.Feeds[i].Fid)">
                                                <i class="mi mi-Like small" data-toggle="tooltip" data-placement="top" title="赞" id="@("likesIcon-" + Model.Feeds[i].Fid)"></i>
                                                <span id="@("likesCount-" + Model.Feeds[i].Fid)">@Model.Feeds[i].Likes</span>
                                            </a>
                                        }
                                    </div>
                                </blockquote>
                            </div>
                        </div>
                    </dd>
                }
                <dt class="bg-gray">……</dt>
            </dl>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.VivaTimeline').vivaTimeline({
            carousel: true,
            carouselTime: 3000
        });
    });
</script>

Views/Home/Filing.cshtml
@using FluentBlog.Models
@model FluentBlog.ViewModels.FilingViewModel

<div class="card mb-4 shadow">
    <!--主体-->
    <div class="card-body">
        <div class="p-3">
            <!--标题-->
            <h2 class="card-title font-weight-bold mb-2 mt-3">
                归档
            </h2>
            <p>当前博客共收录文章@(Model.Count.Item1)篇，分类@(Model.Count.Item2)个，标签@(Model.Count.Item3)个</p>
        </div>
        <hr>
        <!--tab标签-->
        <ul class="nav nav-tabs fluent-tabs px-3" role="tablist">
            <!--文章-->
            <li class="nav-item">
                <a class="nav-link active" id="archive-tab" data-toggle="tab" href="#archive-tabpanel" aria-selected="true">文章</a>
            </li>
            <!--分类-->
            <li class="nav-item">
                <a class="nav-link" id="category-tab" data-toggle="tab" href="#category-tabpanel" aria-selected="false">分类</a>
            </li>
            <!--标签-->
            <li class="nav-item">
                <a class="nav-link" id="tag-tab" data-toggle="tab" href="#tag-tabpanel" aria-selected="false">标签</a>
            </li>
        </ul>
        <!--tab内容-->
        <div class="tab-content m-0 px-3 py-4">
            <!--文章-->
            <div class="tab-pane fade show active" id="archive-tabpanel">
                <!--年份-->
                @foreach (var archivesOfYear in Model.Archives)
                {
                    <div class="pb-3">
                        <!--显示按钮-->
                        <div>
                            <a data-toggle="collapse" href="#@("year-" + archivesOfYear[0][0].Created.Year)">
                                <h4>
                                    <i class="mi collapse-icon"></i>
                                    @archivesOfYear[0][0].Created.Year 年
                                </h4>
                            </a>
                        </div>
                        <!--隐藏内容（默认显示）-->
                        <div class="collapse show" id="@("year-" + archivesOfYear[0][0].Created.Year)">
                            <!--月份-->
                            <div class="pl-4">
                                @foreach (var archivesOfMonth in archivesOfYear)
                                {
                                    <div class="pb-2">
                                        <!--显示按钮-->
                                        <a data-toggle="collapse" href="#@("month-" + archivesOfMonth[0].Created.Year + "-" + @archivesOfMonth[0].Created.Month)">
                                            <h5>
                                                <i class="mi collapse-icon"></i>
                                                @archivesOfMonth[0].Created.Month 月
                                            </h5>
                                        </a>
                                        @foreach (var archive in archivesOfMonth)
                                        {
                                            <!--隐藏内容（默认显示）-->
                                            <div class="collapse show" id="@("month-" + archivesOfMonth[0].Created.Year + "-" + @archivesOfMonth[0].Created.Month)">
                                                <div class="pl-4">
                                                    <!--文章标题-->
                                                    <a class="text-dark text-decoration-none font-weight-normal" asp-controller="Home" asp-action="Archive" asp-route-aid="@archive.Aid">- @archive.Title</a>
                                                    <!--文章浏览量和评论数-->
                                                    <span class="d-md-block d-none float-right">
                                                        <i class="mi mi-View"></i> @archive.Views
                                                        -
                                                        <i class="mi mi-Comment"></i> @archive.CommentsNum
                                                    </span>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!--分类-->
            <div class="tab-pane fade" id="category-tabpanel">
                @for (int i = 0; i < Model.Categories.Item1.Count; i++)
                {
                    <a class="btn @Model.CategoryColors[i % 5]" asp-controller="Home" asp-action="Index" asp-route-slug="@Model.Categories.Item1[i].Slug">
                        @Model.Categories.Item1[i].Name (@Model.Categories.Item2[i])
                    </a>
                }
            </div>
            <!--标签-->
            <div class="tab-pane fade" id="tag-tabpanel">
                @for (int i = 0; i < Model.Tags.Item1.Count; i++)
                {
                    <a class="p-2" asp-controller="Home" asp-action="Index" asp-route-slug="@Model.Tags.Item1[i].Slug">
                        #@Model.Tags.Item1[i].Name (@Model.Tags.Item2[i])
                    </a>
                }
            </div>
        </div>
    </div>
</div>

@section SecondSidebar{
    <!-- 动态栏 -->
    @if (ViewBag.Settings["FeedSwitch"] == "on")
    {
        @await Component.InvokeAsync("FeedBlock")
    }
    <!-- 热门文章 -->
    @await Component.InvokeAsync("TopArchivesBlock")
}